### PR TITLE
fix bitops2 checkedScan and bitScan for vcc

### PR DESCRIPTION
**Pull request by jangko**

### CODE REVIEW

**Comment by arnetheduck** [comment]
this is not covered by tests?

**Comment by jangko** [comment]
our appveyor configuration using mingw-gcc, not vcc. so the answer is yes, all vcc related code are not tested.

**Comment by zah** [comment]
It should be possible to add Visual Studio targets though:
https://www.appveyor.com/docs/lang/cpp/#visual-studio

**Comment by jangko** [comment]
one thing I hate about Nim default `nim.cfg` regarding vcc is Nim will call vcc by a proxy executable called `vccexe.exe` which slow down compilation tremendously.

**Pull request merged**
