### PR TITLE
move `-d:nimRawSetjmp` to config.nim

### PR DESCRIPTION
**Pull request by narimiran**
Refs https://github.com/status-im/nimbus-build-system/issues/44

### CODE REVIEW

**Comment by Menduist** [comment]
I've cancelled this run since it will fail on windows and our CI is slightly overloaded :)

**Comment by narimiran** [comment]
> our CI is slightly overloaded

Ok, I'll delay pushing similar changes to other repos for tomorrow.

**Comment by arnetheduck** [comment]
>  (this is only needed in this repo since we test with vcc)

I think better add "not vcc" in all repos - this is not something to research again

**Comment by arnetheduck** [comment]
per discussion in #nim-opportunities, let's use `.cfg` files for simple options

**Comment by narimiran** [comment]
> per discussion in #nim-opportunities, let's use `.cfg` files for simple options

Ok, done. (And I'll make the same change in other repos too)

**Review by arnetheduck — APPROVED** [review]

**Comment by arnetheduck** [comment]
So, this looks like it might need investigation on the nim side:


nim.cfg:
```
@if vcc
  -d:testit
@end
```

test.nim:
```
when defined(testit):
  {.error: "vcc in config".}
else:
  {.error: "vcc not in config".}
```

```
nim c --cc:vcc -c test.nim
```

this prints "vcc not in config" on my (linux) nim

**Comment by narimiran** [comment]
> `nim c --cc:vcc -r test.nim`

It seems that `--cc:...` is not picked up at all!
Because if I change the `nim.cfg` to `@if gcc: ...` it says `Error: vcc in config` regardless of what I pass to `--cc`.

**Pull request closed without merging**
